import * as T from 'three';
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader.js';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id),A=window.WRAITH_ASSETS,V=$('viewport');
const labels=['Three-quarter study','Lateral silhouette','Upper surfaces','Underbody architecture','Reverse perspective'];
A.images.forEach((src,i)=>{let b=document.createElement('button');b.innerHTML=`<img src="${src}" alt="${labels[i]}" loading="lazy"><span>0${i+1} / ${labels[i]}</span>`;b.onclick=()=>{$('imageDialog').querySelector('img').src=src;$('imageDialog').showModal()};$('gallery').append(b)});$('closeImage').onclick=()=>$('imageDialog').close();
let renderer,scene,camera,controls,rig,parts=[],mats=[],flames=[],demo=false,theme='black',selection=null,elapsed=0;const state={explode:0,gear:0,throttle:0,hover:0};
try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;V.prepend(renderer.domElement);scene=new T.Scene();scene.background=new T.Color('#080b10');scene.fog=new T.Fog('#080b10',22,60);camera=new T.PerspectiveCamera(38,1,.05,120);camera.position.set(11,6,13);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=28;controls.maxPolarAngle=Math.PI*.93;controls.target.set(0,1.8,0);controls.addEventListener('start',()=>{stopDemo();goal=null});
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();scene.add(new T.HemisphereLight(0xc7e1ff,0x384150,2));
const key=new T.DirectionalLight(0xffeee1,4);key.position.set(5,10,7);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:.5,far:35});key.shadow.bias=-.0003;scene.add(key);const fill=new T.DirectionalLight(0xa1c9ff,3);fill.position.set(-8,4,-4);scene.add(fill);const rim=new T.DirectionalLight(0xff566c,2);rim.position.set(2,5,-8);scene.add(rim);
const ground=new T.Mesh(new T.PlaneGeometry(180,180),new T.MeshStandardMaterial({color:0x0c1017,roughness:.34,metalness:.42}));ground.rotation.x=-Math.PI/2;ground.position.y=-.18;ground.receiveShadow=true;scene.add(ground);
const platform=new T.Mesh(new T.CylinderGeometry(7.4,7.5,.2,128),new T.MeshStandardMaterial({color:0x151b23,roughness:.28,metalness:.65}));platform.position.y=-.1;platform.receiveShadow=true;scene.add(platform);const ring=new T.Mesh(new T.TorusGeometry(7.25,.012,6,160),new T.MeshBasicMaterial({color:0xa72b3c}));ring.rotation.x=Math.PI/2;ring.position.y=.012;scene.add(ring);
rig=new T.Group();scene.add(rig);const manager=new T.LoadingManager();manager.setURLModifier(url=>{const name=decodeURIComponent(url).split(/[\\/]/).pop();return A.textures[name]||url});const bytes=Uint8Array.from(atob(A.fbx),x=>x.charCodeAt(0));const original=new FBXLoader(manager).parse(bytes.buffer,'');original.updateMatrixWorld(true);const box=new T.Box3().setFromObject(original),center=box.getCenter(new T.Vector3()),scale=12/box.getSize(new T.Vector3()).z;
const names={Cube:'Integrated body / cockpit',Cube003:'Aft outer housings',Cube008:'Forward lower fairings',Cube004:'Aft support assembly',Cube005:'Central support foot',Cylinder002:'Aft mechanical linkage',Cylinder004:'Forward cross member',Cylinder:'Twin exhaust assembly',Cube006:'Aft upper struts',Cube007:'Aft outer struts',Cube010:'Forward outer struts',Torus003:'Central support spring',Cylinder003:'Central support shaft',Cube009:'Forward inner struts',Torus004:'Forward lower mechanism'};
original.traverse(o=>{if(!o.isMesh)return;const geo=o.geometry.clone();geo.applyMatrix4(o.matrixWorld);geo.translate(-center.x,-box.min.y,-center.z);geo.scale(scale,scale,scale);geo.computeBoundingBox();const c=geo.boundingBox.getCenter(new T.Vector3());geo.translate(-c.x,-c.y,-c.z);const material=(Array.isArray(o.material)?o.material:[o.material]).map(old=>{let n=old.name.toLowerCase();let m=new T.MeshPhysicalMaterial({name:old.name,color:old.color, map:old.map,metalness:n.includes('base')?.62:n.includes('steel')?.9:.25,roughness:n.includes('base')?.28:.46,clearcoat:n.includes('base')?1:.25,clearcoatRoughness:.18,side:T.DoubleSide});if(n.includes('base'))m.color.set('#b50920');if(n.includes('light')){m.emissive.set(n.includes('2')?'#ffbd24':'#cceaff');m.emissiveIntensity=2}if(n==='glass'){m.color.set('#162334');m.metalness=.8;m.roughness=.12}m.userData={paint:n.includes('base'),light:n.includes('light')};mats.push(m);return m});const p=new T.Mesh(geo,material);p.name=o.name;p.position.copy(c);p.castShadow=true;p.receiveShadow=true;p.userData={base:c.clone(),label:names[o.name]||o.name,dir:new T.Vector3(c.x*.6,c.y*.75+.5,c.z*.4),support:['Cube005','Torus003','Cylinder003'].includes(o.name)};parts.push(p);rig.add(p);const b=document.createElement('button');b.textContent=p.userData.label;b.onclick=()=>{selection=selection===p?null:p;$('parts').querySelectorAll('button').forEach(x=>x.classList.remove('active'));if(selection)b.classList.add('active')};$('parts').append(b)});
let triangles=parts.reduce((n,p)=>n+(p.geometry.index?p.geometry.index.count:p.geometry.attributes.position.count)/3,0);$('analysis').textContent=`15 authored mesh objects; ${triangles.toLocaleString()} triangles; no animation clips or skeleton. The main body combines the cockpit, fins and multiple surfaces, so these remain intact. Separation moves original mesh objects. Central support retraction is a conceptual vertical movement. Exhaust effects are added for presentation. Part descriptions are inferred from mesh locations; original object names are preserved in the analysis file.`;
for(const x of [-.27,.27]){const f=new T.Mesh(new T.ConeGeometry(.17,1.9,24,1,true),new T.MeshBasicMaterial({color:0x60ccff,transparent:true,opacity:.6,depthWrite:false,blending:T.AdditiveBlending,side:T.DoubleSide}));f.rotation.x=-Math.PI/2;f.position.set(x,1.03,-6);rig.add(f);flames.push(f)}
$('loading').style.display='none';$('renderStatus').textContent='REALTIME / PBR';
const resize=()=>{const w=V.clientWidth,h=V.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(V);resize();
let goal=null;const views={hero:[11,6,13],side:[15,3,0],front:[0,3,17],rear:[0,3,-17],top:[0,18,.01],bottom:[0,-14,.01]};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{stopDemo();$('rotate').checked=false;rig.rotation.set(0,0,0);goal=new T.Vector3(...views[b.dataset.view]);controls.target.set(0,1.7,0);document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('viewLabel').textContent='VIEW / '+b.textContent.toUpperCase();ground.visible=platform.visible=ring.visible=b.dataset.view!=='bottom'});
document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{theme=b.dataset.theme;document.body.className=theme;document.querySelectorAll('[data-theme]').forEach(x=>x.classList.toggle('active',x===b));let white=theme==='white';scene.background.set(white?'#dce2e7':'#080b10');scene.fog.color.copy(scene.background);ground.material.color.set(white?'#c7ced5':'#0c1017');platform.material.color.set(white?'#e2e6e9':'#151b23');renderer.toneMappingExposure=white?1:1.25;rim.color.set(theme==='night'?'#7fff90':'#ff566c')});
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{mats.filter(m=>m.userData.paint).forEach(m=>m.color.set(b.dataset.color));$('paintName').textContent=b.getAttribute('aria-label');document.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('active',x===b))});
['rough','explode','gear','throttle'].forEach(id=>$(id).oninput=()=>{stopDemo();$(id+'Out').value=$(id).value+'%';if(id==='rough')mats.filter(m=>m.userData.paint).forEach(m=>m.roughness=+$(id).value/100)});$('wire').onchange=()=>mats.forEach(m=>m.wireframe=$('wire').checked);$('lights').onchange=()=>mats.filter(m=>m.userData.light).forEach(m=>m.emissiveIntensity=$('lights').checked?2:0);
$('demo').onclick=()=>{demo=!demo;elapsed=0;$('demo').textContent=demo?'Ⅱ Stop cinematic demo':'▶ Play cinematic demo';if(demo){goal=null;ground.visible=platform.visible=ring.visible=true;$('hover').checked=true;$('rotate').checked=false}};
$('reset').onclick=()=>{stopDemo();['explode','gear','throttle'].forEach(id=>{$(id).value=0;$(id+'Out').value='0%'});$('hover').checked=$('rotate').checked=$('wire').checked=false;$('lights').checked=true;$('lights').onchange();$('wire').onchange();$('rough').value=28;$('rough').oninput();selection=null;document.querySelector('[data-color]').click();document.querySelector('[data-theme]').click();document.querySelector('[data-view="hero"]').click();$('parts').querySelectorAll('button').forEach(x=>x.classList.remove('active'))};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await V.requestFullscreen()}catch{$('renderStatus').textContent='FULLSCREEN UNAVAILABLE'}};$('snapshot').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download='Crimson-Wraith-XV-01.png';a.href=renderer.domElement.toDataURL('image/png');a.click()};
const clock=new T.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;elapsed+=dt;if(demo){camera.position.set(Math.sin(elapsed*.17)*16,5+Math.sin(elapsed*.11)*2,Math.cos(elapsed*.17)*16);controls.target.set(0,1.8,0);let phase=elapsed%32;$('explode').value=phase>18&&phase<26?Math.sin((phase-18)/8*Math.PI)*60:0;$('gear').value=phase>5&&phase<18?100:0;$('throttle').value=phase<18?60+Math.sin(elapsed)*20:0;['explode','gear','throttle'].forEach(id=>$(id+'Out').value=Math.round($(id).value)+'%')}
for(const id of ['explode','gear','throttle'])state[id]=T.MathUtils.damp(state[id],+$(id).value/100,5,dt);state.hover=T.MathUtils.damp(state.hover,$('hover').checked?1:0,3,dt);rig.position.y=state.hover*(.45+Math.sin(t*1.5)*.09);rig.rotation.z=state.hover*Math.sin(t*.8)*.012;if($('rotate').checked)rig.rotation.y+=dt*.17;
parts.forEach(p=>{p.position.copy(p.userData.base);if(p.name!=='Cube')p.position.addScaledVector(p.userData.dir,state.explode*1.6);if(p.userData.support)p.position.y+=state.gear*.32;p.material.forEach(m=>{m.opacity=selection&&selection!==p?.18:1;m.transparent=m.opacity<1;m.depthWrite=m.opacity===1})});flames.forEach((f,i)=>{f.visible=state.throttle>.015;f.scale.set(1,Math.max(.01,state.throttle*(1+Math.sin(t*36+i)*.08)),1);f.material.opacity=.35+state.throttle*.35});if(goal){camera.position.lerp(goal,1-Math.exp(-dt*4));if(camera.position.distanceTo(goal)<.02)goal=null}controls.update();$('power').innerHTML=String(Math.round(state.throttle*100)).padStart(2,'0')+' <small>% intensity</small>';$('mode').innerHTML=(demo?'Cinematic':state.explode>.05?'Assembly':state.hover>.2?'Hover':'Stationary')+' <small>/ studio</small>';renderer.render(scene,camera)}animate();
}catch(e){console.error(e);$('loading').innerHTML='<strong>3D view could not start</strong><span>Enable WebGL in a current browser. The original views remain available below.</span>';}
function stopDemo(){demo=false;$('demo').textContent='▶ Play cinematic demo'}
